### PR TITLE
INFRA-135: Fixing PowerShell analyzer warning suppressions

### PR DESCRIPTION
**Pull request by BenedekFarkas**

### CODE REVIEW

**Review by Piedone — APPROVED** [review]
Why didn't these cause issues when run from GHA, BTW?

**Comment by BenedekFarkas** [comment]
> Why didn't these cause issues when run from GHA, BTW?

If Swap worked from GHA, then I don't know, because the same failure happens under PS Core, not just Windows PS (and both GHA and TC use the dev branch of this repo).

**Comment by Piedone** [comment]
It worked without issues, yes.

**Comment by BenedekFarkas** [comment]
¯\\_(ツ)_/¯

**Pull request merged**
